export const SEARCH_FOCUS ='header/seadrchfocus'
export const SEARCH_BLUR ='header/seachblur'
export const GET_LIST ='header/getlist'
export const MOUSE_ENTER ='header/mouseenter'
export const MOUSE_LEAVE ='header/mouseleave'
export const CHANGE_PAGE ='header/changepage'